### ISSUE TITLE
[Bug]: text insert fail

### ISSUE THREAD

**Issue by yangjie407** [infiniflow/infinity#1046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

e3bdb42

### Actual behavior

I wanna insert geonames dataset, but it fails at the line of 1360000.
The output is shown below:
File ".../transport/TSocket.py", line 169, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x77edf97fac00>

### Steps to reproduce

```Markdown
db_obj = infinity_obj.get_database("default")
db_obj.drop_table("geonames")
table_obj = db_obj.create_table("geonames", {"name": "varchar",  
                                             "feature_class": "varchar",
                                             "cc2": "varchar",
                                             "timezone": "varchar",
                                             "dem": "varchar",
                                             "country_code": "varchar",
                                             "admin1_code": "varchar",
                                             "admin2_code": "varchar",
                                             "admin3_code": "varchar",
                                             "admin4_code": "varchar",
                                             "feature_code": "varchar",
                                             "alternatenames": "varchar",
                                             "asciiname": "varchar"}, 
                                             ConflictType.Error)
fields = ["name", "feature_class", "cc2", "timezone", "dem", "country_code", "admin1_code", "admin2_code", "admin3_code", "admin4_code", "feature_code", "alternatenames", "asciiname"]
with open(geonames_file_path, 'r') as file:
    values = []
    for i, line in enumerate(file):
        if i!=0 and i % 5000 == 0:
            res = table_obj.insert(values)
            assert res.error_code == ErrorCode.OK
            values = []
        record = json.loads(line)
        value = {}
        for field in fields:
            value[field] = record.get(field, "233")
        values.append(value)
    if len(values):
        table_obj.insert(values)
```

**Comment by small-turtle-1** [comment]
Traceback (most recent call last):
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/./python/tmp_test.py", line 56, in <module>
    table_obj.insert(values)
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/table.py", line 171, in insert
    res = self._conn.insert(db_name=db_name, table_name=table_name, column_names=column_names,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/client.py", line 124, in insert
    return self.client.Insert(InsertRequest(session_id=self.session_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 426, in Insert
    return self.recv_Insert()
           ^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 438, in recv_Insert
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 166, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x76d58276aac0>
Traceback (most recent call last):
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity.py", line 36, in __del__
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity.py", line 96, in disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/client.py", line 178, in disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 265, in Disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity3/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 274, in send_Disconnect
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 179, in flush
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 185, in write
thrift.transport.TTransport.TTransportException: unexpected exception

**Comment by small-turtle-1** [comment]
thrift 0.20

Insert 8890000 records
Traceback (most recent call last):
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/./python/tmp_test.py", line 56, in <module>
    table_obj.insert(values)
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/table.py", line 171, in insert
    res = self._conn.insert(db_name=db_name, table_name=table_name, column_names=column_names,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/client.py", line 124, in insert
    return self.client.Insert(InsertRequest(session_id=self.session_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 426, in Insert
    return self.recv_Insert()
           ^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 438, in recv_Insert
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 169, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x728ad1d520c0>
Traceback (most recent call last):
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity.py", line 36, in __del__
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity.py", line 96, in disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/client.py", line 178, in disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 265, in Disconnect
  File "/home/shenyushi/Documents/Github/infiniflow/infinity/python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 274, in send_Disconnect
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 179, in flush
  File "/home/shenyushi/anaconda3/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 188, in write
thrift.transport.TTransport.TTransportException: unexpected exception

**Comment by JinHai-CN** [comment]
Work around solution: #1061
