### ISSUE TITLE
[Bug]: insert enwiki datasets failed

### ISSUE THREAD

**Issue by yangjie407** [infiniflow/infinity#1125]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

a144119

### Actual behavior

When I insert enwiki datasets into infinity (line by line), I encounted the exception below:
Traceback (most recent call last):
  File "/home/ubuntu/infinity/python/benchmark/run.py", line 65, in <module>
    client.run_experiment(args)
  File "/home/ubuntu/infinity/python/benchmark/clients/base_client.py", line 70, in run_experiment
    self.upload()
  File "/home/ubuntu/infinity/python/benchmark/clients/infinity_client.py", line 73, in upload
    table_obj.insert(actions)
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/table.py", line 214, in insert
    raise Exception(f"ERROR:{res.error_code}, {res.error_msg}")
Exception: ERROR:5003, retry insert failed
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x7fdcd1655d00>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/infinity.py", line 36, in __del__
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/infinity.py", line 96, in disconnect
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/client.py", line 201, in disconnect
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 305, in Disconnect
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 314, in send_Disconnect
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 179, in flush
  File "/home/ubuntu/anaconda3/envs/openai_test/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 185, in write
thrift.transport.TTransport.TTransportException: unexpected exception

### Steps to reproduce

```Markdown
insert enwiki.csv into infinity.
```

**Comment by Ognimalf** [comment]
It's ok on my machine, even if I set the retry times to 1 in python client.

**Comment by yuzhichang** [comment]
Fixed by #1156
