### ISSUE TITLE
[Bug]: Infinity can not start up correctly with segment error

### ISSUE THREAD

**Issue by yingfeng** [infiniflow/infinity#1129]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

8cd2c2ebb2844739f6514219ef17cf19a3dc6f28

### Actual behavior

The coredump of starting up error: 
```
Thread 1 "infinity" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d7dca8 in __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:(gdb) bt
#0  0x00007ffff7d7dca8 in __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:833
#1  0x00005555558e481e in std::char_traits<char>::copy (__s1=<optimized out>, __s2=<optimized out>, __n=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/char_traits.h:445
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (
    __d=0x7fff3aa00a40 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", __s=0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003",
    __n=2037672302) at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/basic_string.h:420
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (
    __p=0x7fff3aa00a40 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", __k1=0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003",
    __k2=0x800070f9bec3 <error: Cannot access memory at address 0x800070f9bec3>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/basic_string.h:474
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=0x7fffffffcbd8,
    __beg=0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", __end=0x800070f9bec3 <error: Cannot access memory at address 0x800070f9bec3>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/basic_string.tcc:243
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffcbd8,
    __s=0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", __n=2037672302, __a=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/basic_string.h:617
#6  infinity::ReadBufAdv<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (
    buf=@0x7fffffffd218: 0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003")
    at /home/infominer/codebase/workspace/infinity/src/parser/type/serialize.h:68
#7  infinity::AddTableEntryOp@catalog_delta_entry::ReadAdv(char*&, char*) (
    ptr=@0x7fffffffd218: 0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", ptr_end=ptr_end@entry=0x7ffff78555ff "")
    at /home/infominer/codebase/workspace/infinity/src/storage/wal/catalog_delta_entry.cpp:292
#8  0x00005555558e3f81 in infinity::CatalogDeltaOperation@catalog_delta_entry::ReadAdv(char*&, int) (
    ptr=@0x7fffffffd218: 0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", max_bytes=max_bytes@entry=235)
    at /home/infominer/codebase/workspace/infinity/src/storage/wal/catalog_delta_entry.cpp:98
#9  0x00005555558ead5b in infinity::CatalogDeltaEntry@catalog_delta_entry::ReadAdv(char*&, int) (
    ptr=@0x7fffffffd218: 0x7ffff7855555 "/data/NznNpdllFS_db_default_db/18A7iGnxiV_table_wiki\003", max_bytes=<optimized out>)
    at /home/infominer/codebase/workspace/infinity/src/storage/wal/catalog_delta_entry.cpp:860
#10 0x00005555558228cf in infinity::Catalog@catalog::LoadFromFileDelta(infinity::DeltaCatalogFileInfo@log_file const&) (delta_ckp_info=...)
    at /home/infominer/codebase/workspace/infinity/src/storage/meta/catalog.cpp:484
#11 0x0000555555822216 in infinity::Catalog@catalog::LoadFromFiles(infinity::FullCatalogFileInfo@log_file const&, std::vector<infinity::DeltaCatalogFileInfo@log_file, std::allocator<infinity::DeltaCatalogFileInfo@log_file> > const&, infinity::BufferManager@buffer_manager*) (full_ckp_info=..., delta_ckp_infos=...,
--Type <RET> for more, q to quit, c to continue without paging--
    buffer_mgr=0x7ffff7851180) at /home/infominer/codebase/workspace/infinity/src/storage/meta/catalog.cpp:462
#12 0x00005555558cd4c3 in infinity::Storage@storage::AttachCatalog(infinity::FullCatalogFileInfo@log_file const&, std::vector<infinity::DeltaCatalogFileInfo@log_file, std::allocator<infinity::DeltaCatalogFileInfo@log_file> > const&) (this=0x7ffff7850740, full_ckp_info=..., delta_ckp_infos=...)
    at /home/infominer/codebase/workspace/infinity/src/storage/storage.cpp:172
#13 0x00005555559073fa in infinity::WalManager@wal_manager::ReplayWalFile() (this=0x7ffff7832400)
    at /home/infominer/codebase/workspace/infinity/src/storage/wal/wal_manager.cpp:490
#14 0x00005555558cc62b in infinity::Storage@storage::Init() (this=0x7ffff7850740) at /home/infominer/codebase/workspace/infinity/src/storage/storage.cpp:64
#15 0x0000555555764804 in infinity::InfinityContext@infinity_context::Init(std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) (this=0x555556308a60 <infinity::Singleton@singleton<infinity::InfinityContext@infinity_context>::instance()::instance>, config_path=...)
    at /home/infominer/codebase/workspace/infinity/src/main/infinity_context.cpp:46
#16 0x0000555555602179 in main (argc=1, argv=<optimized out>) at /home/infominer/codebase/workspace/infinity/src/bin/infinity_main.cpp:177
```

### Steps to reproduce

```Markdown
After importing 35M enwiki datasets, then restart infinity
```

**Comment by yingfeng** [comment]
close due to incompatible wal format
