### ISSUE TITLE
[Bug]: Deleting data using two columns of string fields as filtering conditions can cause the database to crash

### ISSUE THREAD

**Issue by joynn** [infiniflow/infinity#1662]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Version or Commit ID

v0.3.0.dev4

### Other environment information

```Markdown
ubuntu24.04
```

### Actual behavior and How to reproduce it

My data is approximately like the following.
┌────┬─────┬──┬─────┬─────────┐
│  kb_id┆  file_id ┆ … ┆ content ┆ embedding  │
│ ---      ┆ ---        ┆--- ┆   ---        ┆    ---                │
│ str      ┆ str        ┆str┆ str          ┆ list[f64]          │
╞════╪═════╪══╪═════╪═════════╪
│ aaa    ┆ bbb     ┆  … ┆ ccc       ┆ [1.0, 2.0,          │
└────┴────┴───┴─────┴─────────┘
When using    `table.delete("kb_id = 'aaa'")`    the function works properly，
When using    `table.delete("kb_id = 'aaa' and file_id = 'bbb'")` , the database will crash.

The database error log is as follows:
`libc++abi: terminating due to uncaught exception of type infinity::UnrecoverableException@infinity_exception: Invalid column index@src/executor/expression/expression_evaluator.cpp:187`

The local error log is as follows:
```
Traceback (most recent call last):
  File "……/connector/database/infinity/infinity_client.py", line 170, in <module>
    client.delete_files("2323fas","23fawsefas")
  File "……/connector/database/infinity/infinity_client.py", line 129, in delete_files
    table.delete("kb_id='2323fas' and file_id = '23fawsefas'")
  File "……/python3.12/site-packages/infinity/remote_thrift/table.py", line 306, in delete
    res = self._conn.delete(
          ^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/infinity/remote_thrift/client.py", line 223, in delete
    return self.client.Delete(DeleteRequest(session_id=self.session_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 637, in Delete
    return self.recv_Delete()
           ^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 649, in recv_Delete
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "……/python3.12/site-packages/thrift/transport/TSocket.py", line 169, in read
    raise TTransportException(type=TTransportException.END_OF_FILE,
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x7f1f78d62d40>
Traceback (most recent call last):
  File "……/python3.12/site-packages/infinity/remote_thrift/infinity.py", line 35, in __del__
    self.disconnect()
  File "……/python3.12/site-packages/infinity/remote_thrift/infinity.py", line 96, in disconnect
    if res.error_code == ErrorCode.OK:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'error_code'
```

### Expected behavior

The example code that was delete used int columns . Is there a feature for delete based on multiple str columns

**Comment by joynn** [comment]
This function seems to be normal in 0.3.0.dev5
