### ISSUE TITLE
[Bug]: The service crashes when running python sdk tests.

### ISSUE THREAD

**Issue by Ognimalf** [infiniflow/infinity#849]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f86d061

### Actual behavior

When running python sdk tests and after finishing `test_insert.py:test_insert_big_embedding` , the service crash down. The info of AddressSanitizer is below:

```
=================================================================
==494060==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x508000004268 at pc 0x561d4294d2b2 bp 0x7fd9ae85bf70 sp 0x7fd9ae85bf68
READ of size 4 at 0x508000004268 thread T17
[20:17:39.739] [494079] [info] Save delta catalog to: /tmp/infinity/data/catalog/CATALOG_DELTA_ENTRY.DELTA.14990, size: 6121.
[20:17:43.478] [494080] [info] Cleanup visible timestamp: 14991
    #0 0x561d4294d2b1 in infinity::BufferObj@buffer_obj::Free() /home/xwg/dev/infinity/src/storage/buffer/buffer_obj.cpp:100:13
    #1 0x561d429448c4 in infinity::BufferManager@buffer_manager::RequestSpace(unsigned long, infinity::BufferObj@buffer_obj*) /home/xwg/dev/infinity/src/storage/buffer/buffer_manager.cpp:94:30
    #2 0x561d4294c744 in infinity::BufferObj@buffer_obj::Load() /home/xwg/dev/infinity/src/storage/buffer/buffer_obj.cpp:65:26
    #3 0x561d41c5a689 in infinity::VectorBuffer@vector_buffer::Initialize(infinity::BufferManager@buffer_manager*, infinity::BlockColumnEntry@block_column_entry*, unsigned long, unsigned long) /home/xwg/dev/infinity/src/storage/column_vector/vector_buffer.cpp:125:24
    #4 0x561d41c592ab in infinity::VectorBuffer@vector_buffer::Make(infinity::BufferManager@buffer_manager*, infinity::BlockColumnEntry@block_column_entry*, unsigned long, unsigned long, infinity::VectorBufferType@vector_buffer) /home/xwg/dev/infinity/src/storage/column_vector/vector_buffer.cpp:58:25
    #5 0x561d41bf2aac in infinity::ColumnVector@column_vector::Initialize(infinity::BufferManager@buffer_manager*, infinity::BlockColumnEntry@block_column_entry*, unsigned long, infinity::ColumnVectorType@column_vector, unsigned long) /home/xwg/dev/infinity/src/storage/column_vector/column_vector.cpp:134:19
    #6 0x561d41d3dfc4 in infinity::BlockColumnEntry@block_column_entry::GetColumnVector(infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/meta/entry/block_column_entry.cpp:108:19
    #7 0x561d41d3e4d4 in infinity::BlockColumnEntry@block_column_entry::Append(infinity::ColumnVector@column_vector const*, unsigned short, unsigned long, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/meta/entry/block_column_entry.cpp:116:36
    #8 0x561d41d48c9c in infinity::BlockEntry@block_entry::AppendData(unsigned long, unsigned long, infinity::DataBlock@data_block*, unsigned short, unsigned short, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/meta/entry/block_entry.cpp:177:36
    #9 0x561d41d9095d in infinity::SegmentEntry@segment_entry::AppendData(unsigned long, unsigned long, infinity::AppendState@data_access_state*, infinity::BufferManager@buffer_manager*, infinity::Txn@txn*) /home/xwg/dev/infinity/src/storage/meta/entry/segment_entry.cpp:273:35
    #10 0x561d41e45ff6 in infinity::TableEntry@table_entry::Append(unsigned long, void*, unsigned long, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/meta/entry/table_entry.cpp:312:50
    #11 0x561d41cd1c24 in infinity::Catalog@catalog::Append(infinity::TableEntry@table_entry*, unsigned long, void*, unsigned long, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/meta/catalog.cpp:323:25
    #12 0x561d420810d3 in infinity::TxnTableStore@txn_store::PrepareCommit(unsigned long, unsigned long, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/txn/txn_store.cpp:247:5
    #13 0x561d420861c4 in infinity::TxnStore@txn_store::PrepareCommit(unsigned long, unsigned long, infinity::BufferManager@buffer_manager*) /home/xwg/dev/infinity/src/storage/txn/txn_store.cpp:404:22
    #14 0x561d420452c3 in infinity::Txn@txn::CommitBottom() /home/xwg/dev/infinity/src/storage/txn/txn.cpp:424:16
    #15 0x561d420e8d21 in infinity::WalManager@wal_manager::Flush() /home/xwg/dev/infinity/src/storage/wal/wal_manager.cpp:216:22
    #16 0x561d42106a09 in infinity::WalManager@wal_manager::Start()::$_0::operator()() const /home/xwg/dev/infinity/src/storage/wal/wal_manager.cpp:87:37
    #17 0x561d421069c4 in void std::__invoke_impl<void, infinity::WalManager@wal_manager::Start()::$_0>(std::__invoke_other, infinity::WalManager@wal_manager::Start()::$_0&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:61:14
    #18 0x561d42106984 in std::__invoke_result<infinity::WalManager@wal_manager::Start()::$_0>::type std::__invoke<infinity::WalManager@wal_manager::Start()::$_0>(infinity::WalManager@wal_manager::Start()::$_0&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:96:14
    #19 0x561d4210695c in void std::thread::_Invoker<std::tuple<infinity::WalManager@wal_manager::Start()::$_0>>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:292:13
    #20 0x561d42106934 in std::thread::_Invoker<std::tuple<infinity::WalManager@wal_manager::Start()::$_0>>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:299:11
    #21 0x561d42106878 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<infinity::WalManager@wal_manager::Start()::$_0>>>::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:244:13
    #22 0x561d44d6fe02 in execute_native_thread_routine thread.o
    #23 0x561d4135c11a in asan_thread_start(void*) asan_interceptors.cpp.o
    #24 0x7fd9c468f6b9 in start_thread nptl/pthread_create.c:444:8
    #25 0x7fd9c471e11f in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

0x508000004268 is located 104 bytes after 96-byte region [0x5080000041a0,0x508000004200)
allocated by thread T1 here:
    #0 0x561d4139ae6d in operator new(unsigned long) (/home/xwg/dev/infinity/build/src/infinity+0x68ee6d) (BuildId: ed50eb3fb94c4fb4d78089d6873de2eff062ebf8)
    #1 0x561d42946b29 in std::__detail::_MakeUniq<infinity::BufferObj@buffer_obj>::__single_object std::make_unique<infinity::BufferObj@buffer_obj, infinity::BufferManager@buffer_manager*, bool, std::unique_ptr<infinity::FileWorker@file_worker, std::default_delete<infinity::FileWorker@file_worker>>>(infinity::BufferManager@buffer_manager*&&, bool&&, std::unique_ptr<infinity::FileWorker@file_worker, std::default_delete<infinity::FileWorker@file_worker>>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:1070:30
    #2 0x561d42944f4f in std::unique_ptr<infinity::BufferObj@buffer_obj, std::default_delete<infinity::BufferObj@buffer_obj>> infinity::MakeUnique@stl<infinity::BufferObj@buffer_obj, infinity::BufferManager@buffer_manager*, bool, std::unique_ptr<infinity::FileWorker@file_worker, std::default_delete<infinity::FileWorker@file_worker>>>(infinity::BufferManager@buffer_manager*&&, bool&&, std::unique_ptr<infinity::FileWorker@file_worker, std::default_delete<infinity::FileWorker@file_worker>>&&) /home/xwg/dev/infinity/src/common/stl.cppm:385:16
    #3 0x561d42942eb2 in infinity::BufferManager@buffer_manager::Allocate(std::unique_ptr<infinity::FileWorker@file_worker, std::default_delete<infinity::FileWorker@file_worker>>) /home/xwg/dev/infinity/src/storage/buffer/buffer_manager.cpp:42:23
    #4 0x561d41c32918 in infinity::FixHeapManager@fix_heap::AllocateChunk() /home/xwg/dev/infinity/src/storage/column_vector/fix_heap.cpp:62:41
    #5 0x561d41c33a54 in infinity::FixHeapManager@fix_heap::Allocate(unsigned long) /home/xwg/dev/infinity/src/storage/column_vector/fix_heap.cpp:88:51
    #6 0x561d41c34de8 in infinity::FixHeapManager@fix_heap::AppendToHeap(char const*, unsigned long) /home/xwg/dev/infinity/src/storage/column_vector/fix_heap.cpp:124:37
    #7 0x561d41c09b04 in infinity::ColumnVector@column_vector::AppendByStringView(std::basic_string_view<char, std::char_traits<char>>, char) /home/xwg/dev/infinity/src/storage/column_vector/column_vector.cpp:1292:79
    #8 0x561d42b49bbb in infinity::PhysicalImport@physical_import::CSVRowHandler(void*) /home/xwg/dev/infinity/src/executor/operator/physical_import.cpp:385:23
    #9 0x561d4322f845 in row_dl /home/xwg/dev/infinity/third_party/zsv/src/zsv_internal.c:327:5
    #10 0x561d4322f845 in cell_and_row_dl /home/xwg/dev/infinity/third_party/zsv/src/zsv_internal.c:373:10
    #11 0x561d4322f845 in zsv_scan_delim /home/xwg/dev/infinity/third_party/zsv/src/zsv_scan_delim.c
    #12 0x561d4322f845 in zsv_scan /home/xwg/dev/infinity/third_party/zsv/src/zsv_internal.c:458:12

Thread T17 created by T0 here:
    #0 0x561d41343ead in pthread_create (/home/xwg/dev/infinity/build/src/infinity+0x637ead) (BuildId: ed50eb3fb94c4fb4d78089d6873de2eff062ebf8)
    #1 0x561d44d6fed8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State>>, void (*)()) (/home/xwg/dev/infinity/build/src/infinity+0x4063ed8) (BuildId: ed50eb3fb94c4fb4d78089d6873de2eff062ebf8)
    #2 0x561d420e6131 in infinity::WalManager@wal_manager::Start() /home/xwg/dev/infinity/src/storage/wal/wal_manager.cpp:87:21
    #3 0x561d42032d05 in infinity::Storage@storage::Init() /home/xwg/dev/infinity/src/storage/storage.cpp:81:15
    #4 0x561d41916f75 in infinity::InfinityContext@infinity_context::Init(std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const&) /home/xwg/dev/infinity/src/main/infinity_context.cpp:46:19
    #5 0x561d4139e08f in main /home/xwg/dev/infinity/src/bin/infinity_main.cpp:137:33
    #6 0x7fd9c4623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Thread T1 created by T0 here:
    #0 0x561d41343ead in pthread_create (/home/xwg/dev/infinity/build/src/infinity+0x637ead) (BuildId: ed50eb3fb94c4fb4d78089d6873de2eff062ebf8)
    #1 0x561d44d6fed8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State>>, void (*)()) (/home/xwg/dev/infinity/build/src/infinity+0x4063ed8) (BuildId: ed50eb3fb94c4fb4d78089d6873de2eff062ebf8)
    #2 0x561d41be488f in std::__detail::_MakeUniq<std::thread>::__single_object std::make_unique<std::thread, void (infinity::TaskScheduler@task_scheduler::*)(infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, long), infinity::TaskScheduler@task_scheduler*, infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, unsigned long&>(void (infinity::TaskScheduler@task_scheduler::*&&)(infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, long), infinity::TaskScheduler@task_scheduler*&&, infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*&&, unsigned long&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:1070:34
    #3 0x561d41bd8a27 in std::unique_ptr<std::thread, std::default_delete<std::thread>> infinity::MakeUnique@stl<std::thread, void (infinity::TaskScheduler@task_scheduler::*)(infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, long), infinity::TaskScheduler@task_scheduler*, infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, unsigned long&>(void (infinity::TaskScheduler@task_scheduler::*&&)(infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*, long), infinity::TaskScheduler@task_scheduler*&&, infinity::BlockingQueue@blocking_queue<infinity::FragmentTask@fragment_task*>*&&, unsigned long&) /home/xwg/dev/infinity/src/common/stl.cppm:385:16
    #4 0x561d41bd337a in infinity::TaskScheduler@task_scheduler::Init(infinity::Config@config const*) /home/xwg/dev/infinity/src/scheduler/task_scheduler.cpp:59:43
    #5 0x561d41bd2de4 in infinity::TaskScheduler@task_scheduler::TaskScheduler(infinity::Config@config const*) /home/xwg/dev/infinity/src/scheduler/task_scheduler.cpp:42:58
    #6 0x561d41918cda in std::__detail::_MakeUniq<infinity::TaskScheduler@task_scheduler>::__single_object std::make_unique<infinity::TaskScheduler@task_scheduler, infinity::Config@config*>(infinity::Config@config*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/unique_ptr.h:1070:34
    #7 0x561d4191738f in std::unique_ptr<infinity::TaskScheduler@task_scheduler, std::default_delete<infinity::TaskScheduler@task_scheduler>> infinity::MakeUnique@stl<infinity::TaskScheduler@task_scheduler, infinity::Config@config*>(infinity::Config@config*&&) /home/xwg/dev/infinity/src/common/stl.cppm:385:16
    #8 0x561d41916e64 in infinity::InfinityContext@infinity_context::Init(std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const&) /home/xwg/dev/infinity/src/main/infinity_context.cpp:41:27
    #9 0x561d4139e08f in main /home/xwg/dev/infinity/src/bin/infinity_main.cpp:137:33
    #10 0x7fd9c4623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/xwg/dev/infinity/src/storage/buffer/buffer_obj.cpp:100:13 in infinity::BufferObj@buffer_obj::Free()
Shadow bytes around the buggy address:
  0x508000003f80: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 fa
  0x508000004000: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x508000004080: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x508000004100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x508000004180: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
=>0x508000004200: fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa
  0x508000004280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x508000004300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x508000004380: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x508000004400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x508000004480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==494060==ABORTING
```

### Steps to reproduce

```Markdown
1. uncommnet the code ahead of test_insert.py:test_insert_big_embedding

# @pytest.mark.skip("Unexpected error.")

2. run python sdk tests.
```

**Comment by Ognimalf** [comment]
Fixed by #861 .
