### ISSUE TITLE
[Bug]: Unknown SIGTERM received during tests.

### ISSUE THREAD

**Issue by Ognimalf** [infiniflow/infinity#950]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

00f919b

### Actual behavior

When running python-sdk test twice without shutdown service in between, python client will crash when execute  `python/test/test_import.py::TestImport::test_import_exceeding_rows`  , and the service will receive a  `SIGTERM`  signal then shutdown without error.

### Steps to reproduce

```Markdown
1. run python-sdk test.
2. NOT shutdown service and KEEP it ALIVE.
3. run python-sdk test again.
```

**Comment by Ognimalf** [comment]
The log from the Python test is as follows. I suspect that the error might originate from the Python client. This is because when the service receives a SIGTERM signal, the  `thrift_server`  thread should still be active.
For sure I have reinstalled the python sdk locally, and the bug can be reproducible.
```
python/test/test_import.py ...x..................................................................E

================================================================ ERRORS =================================================================
________________________________ ERROR at teardown of TestImport.test_import_exceeding_rows[check_data0] ________________________________
E   thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
--------------------------------------------------------- Captured stdout call ----------------------------------------------------------
              c1                            c2
0              0  asdasdlk中fjio@!#!@asd #$%$23
1              1  asdasdlk中fjio@!#!@asd #$%$23
2              2  asdasdlk中fjio@!#!@asd #$%$23
3              3  asdasdlk中fjio@!#!@asd #$%$23
4              4  asdasdlk中fjio@!#!@asd #$%$23
...          ...                           ...
8388603  8388603  asdasdlk中fjio@!#!@asd #$%$23
8388604  8388604  asdasdlk中fjio@!#!@asd #$%$23
8388605  8388605  asdasdlk中fjio@!#!@asd #$%$23
8388606  8388606  asdasdlk中fjio@!#!@asd #$%$23
8388607  8388607  asdasdlk中fjio@!#!@asd #$%$23

[8388608 rows x 2 columns]
======================================================== short test summary info ========================================================
ERROR python/test/test_import.py::TestImport::test_import_exceeding_rows[check_data0] - thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 221 passed, 190 deselected, 1 xfailed, 1 error in 28.74s ========================================
Exception ignored in: <function RemoteThriftInfinityConnection.__del__ at 0x7f0e7f72e520>
Traceback (most recent call last):
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/infinity/remote_thrift/infinity.py", line 36, in __del__
    self.disconnect()
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/infinity/remote_thrift/infinity.py", line 96, in disconnect
    res = self._client.disconnect()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/infinity/remote_thrift/client.py", line 178, in disconnect
    res = self.client.Disconnect(CommonRequest(session_id=self.session_id))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 265, in Disconnect
    self.send_Disconnect(request)
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py", line 274, in send_Disconnect
    self._oprot.trans.flush()
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 179, in flush
    self.__trans.write(out)
  File "/home/xwg/miniconda3/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 185, in write
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception
An error occurred: None
(base) 
```
